supportsCompareCriteriaEquals: false
supportsInCriteria: false
supportsLikeCriteria: false
supportsOrCriteria: false
supportsRowLimit: false
supportsRowOffset: false
supportsNotCriteria: false
supportsOnlyLiteralComparison: false
supportsLikeCriteriaEscapeCharacter: false
useAnsiJoin: false
